---
- name: create directories for tls assets
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ tls_ca_dir }}"
    - "{{ tls_node_dir }}"
  delegate_to: localhost

- stat:
    path: "{{ tls_ca_cert }}"
  register: tls_ca_cert_output
  delegate_to: localhost

- stat:
    path: "{{ tls_ca_key }}"
  register: tls_ca_key_output
  delegate_to: localhost

- name: create ca
  shell: "cfssl gencert -initca {{ tls_config_dir }}/ca-csr.json | cfssljson -bare ca -"
  args:
    chdir: "{{ tls_ca_dir }}"
  register: create_ca_output
  when: tls_ca_cert_output.stat.exists == False and tls_ca_key_output.stat.exists == False
  delegate_to: localhost